config/routes.rb
NetrunnerCotd::Application.routes.draw do
  get '/selection/cotd', to: 'selection#cotd'

  resources :selection, :only => [:index, :show]

  get '/card/:code', to: 'card#show'
  get '/', to: redirect('/selection/cotd')
end

app/models/card.rb
class Card < ActiveRecord::Base

end

app/models/selection.rb
class Selection < ActiveRecord::Base
  belongs_to :card, foreign_key: :card_code, primary_key: :code

  def self.of_today
    Selection.where(when: Date.today).order(created_at: :desc).first
  end

  def self.get_or_create_of_today
    todays_card = Selection.of_today
    unless todays_card.present?
      random_card = Card.offset(rand(Card.count)).first
      puts "Selected card for today: #{random_card.code} - '#{random_card.title}'"
      todays_card = Selection.new_selection_for_today(random_card.code)
    end
    todays_card
  end

  def self.new_selection_for_today(card_code)
    selection = Selection.new(card_code: card_code, when: Date.today)
    selection.save!
    selection
  end

  def printable_when
    self.when.strftime('%B %-d, %Y')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/card_controller.rb
class CardController < ApplicationController
  def show
    @card = Card.where(code: params[:code]).first
    render :_card
  end
end

app/controllers/selection_controller.rb
class SelectionController < ApplicationController
  def index
    @selections = Selection.all.includes(:card)
    @selections_by_month = @selections.group_by { |s| s.when.beginning_of_month }
  end

  def show
    @selection = Selection.find(params[:id])
  end

  def cotd
    @selection = Selection.get_or_create_of_today
    render 'selection/show'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/card_helper.rb
module CardHelper
  def netrunner_img(url)
    "http://netrunnerdb.com#{url}"
  end

  def icon_map
    {
      'Credits' => 'credit',
      'Subroutine' => 'subroutine',
      'Link' => 'link',
      'Trash' => 'trash',
      'Recurring Credits' => 'recurring-credit',
      'Asset' => 'asset',
      'Rez' => 'rez',
      'Memory Unit' => 'mu',
      'Click' => 'click',

      '1mu' => '1mu',
      '2mu' => '2mu',
      '3mu' => '3mu',

      'Haas-Bioroid' => 'haas-bioroid',
      'Weyland Consortium' => 'weyland-consortium',
      'Jinteki' => 'jinteki',
      'NBN' => 'nbn',

      'Anarch' => 'anarch',
      'Criminal' => 'criminal',
      'Shaper' => 'shaper',
    }
  end


  def fix_icons(the_text)
    icon_map.each do |k,v|
      the_text = the_text.gsub("[#{k}]", "<i class='icon icon-#{v}'></i>")
    end

    the_text
  end

  def fix_newline(the_text)
    the_text.gsub('\n', '<br />')
  end

  def fix_text(the_text)
    the_text = fix_newline(the_text)
    the_text = fix_icons(the_text)
    the_text
  end
end

app/views/card/_card.haml
.bg-img{class: "card-type-#{card.card_type.downcase}"}
.container
  %h1.card_title= card.title
  %h2.card_subtitle
    %span.card_type>= card.card_type
    - if card.subtype.present?
      %span.card_subtype= ": #{card.subtype}"
  %h3.card_faction{faction: card.faction.downcase}
    = card.faction
  %img.card_img{src: netrunner_img(card.imagesrc)}
  %pre.card_text
    = raw fix_icons card.text
  :css
    .bg-img { background-image: url(#{netrunner_img(card.imagesrc)}); }

app/views/card/cotd.haml
.bg-img{class: "card-type-#{@card.card_type.downcase}"}
.container
  %h1.card_title= @card.title
  %h2.card_subtitle
    %span.card_type>= @card.card_type
    - if @card.subtype.present?
      %span.card_subtype= ": #{@card.subtype}"
  %h3.card_faction{faction: @card.faction.downcase}
    = @card.faction
  %img.card_img{src: netrunner_img(@card.imagesrc)}
  %pre.card_text
    = raw fix_icons @card.text
  :css
    .bg-img { background-image: url(#{netrunner_img(@card.imagesrc)}); }

app/views/layouts/application.haml
!!! 5
%html
  %head
    %title Netrunner Card of the Day
    %meta{name:"viewport", content:"width=device-width, user-scalable=no"}
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags

  %body
    %header
      Netrunner Card of the Day
      .sub-header
        = yield :sub_header
    %section
      = yield
    %footer
      %hr
        Created by
        %a{href: 'https://twitter.com/giladgo'}
          @giladgo

app/views/selection/index.haml
%h1 Previous selections
- @selections_by_month.each do |month, selections|
  .month_title= month.strftime('%B %Y')
  %ul.previous_selection_list
    - selections.each do |selection|
      %li.previous_selection_list_item
        = link_to selection do
          = selection.card.title
          ='-'
          = selection.printable_when

app/views/selection/show.haml
- content_for :sub_header do
  For
  = @selection.printable_when
= render partial: 'card/card', locals: {card: @selection.card}
.previous_selections
  = link_to 'Previous Selections', selection_index_path